version: "3"
services:
  api:
    container_name: 'my-tool-BE'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8550:8080"
    environment:
      - TZ=Asia/Taipei
      - SQLITE_PATH=/sqlite.db
    volumes:
      - ./app:/code/app
    #  - .Side_Project.db:/Side_Project.db
      - "./data/sqlite.db:/sqlite.db"
    restart: unless-stopped