version: "3"
services:
  api:
    container_name: 'my-tool-BE'
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - ${BE_PORT}
    environment:
      - TZ=Asia/Taipei
      - SQLITE_PATH=/sqlite.db
    volumes:
      - ./app:/code/app
      - "./data/sqlite.db:/sqlite.db"
    restart: unless-stopped

  db:
    image: postgres:13.2-alpine
    platform: linux/amd64
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'abcd'
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - ${SQL_PORT}
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT}
    ports:
        - ${ADMIN_PORT}
    volumes:
        - pgadmin-data:/var/lib/pgadmin
    links:
        - "db:pgsql-server"

volumes:
  db-data:
  pgadmin-data:
