version: "3"
services:
  api:
    container_name: 'my-tool-BE'
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "8081:8080"
    environment:
      - TZ=Asia/Taipei
      - SQLITE_PATH=/sqlite.db
    volumes:
      - ./app:/code/app
      - "./data/sqlite.db:/sqlite.db"
    restart: unless-stopped

  db:
    image: postgres:13.2-alpine
    platform: linux/amd64
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: 'postgres' #postgres
      POSTGRES_PASSWORD: 'abcd' #1234
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
        PGADMIN_DEFAULT_EMAIL: 'pths411027@gmail.com'
        PGADMIN_DEFAULT_PASSWORD: 'abcd'
        PGADMIN_LISTEN_PORT: 80
    ports:
        - "8085:80"
    volumes:
        - pgadmin-data:/var/lib/pgadmin
    links:
        - "db:pgsql-server"

volumes:
  db-data:
  pgadmin-data:
